import { apiClient } from './client';
const taskToUi = task => ({ ...task, status: String(task.status || 'TODO').toLowerCase() });
const taskToApi = task => ({ ...task, status: String(task.status || 'todo').toUpperCase() });
const milestoneToUi = milestone => ({ ...milestone, status: String(milestone.status || 'PENDING').toLowerCase() });
export const mapTaskToUiModel = taskToUi; export const mapTaskToApiModel = taskToApi; export const mapMilestoneToUiModel = milestoneToUi;
export const listProjects = async () => (await apiClient.get('/api/projects')).map(p => ({ ...p, status: String(p.status || 'PLANNED').toLowerCase() }));
export const getProject = async id => ({ ...(await apiClient.get(`/api/projects/${id}`)), status: String((await apiClient.get(`/api/projects/${id}`)).status || 'PLANNED').toLowerCase() });
export const listProjectsByUniversity = async id => (await apiClient.get(`/api/projects/university/${id}`)).map(p => ({ ...p, status: String(p.status || 'PLANNED').toLowerCase() }));
export const listProjectsByStatus = status => apiClient.get(`/api/projects/status/${String(status).toUpperCase()}`);
export const createProject = payload => apiClient.post('/api/projects', payload);
export const updateProject = (id, payload) => apiClient.put(`/api/projects/${id}`, payload);
export const deleteProject = id => apiClient.delete(`/api/projects/${id}`);
export const listTeamMembers = projectId => apiClient.get(`/api/projects/${projectId}/team`);
export const addTeamMember = (projectId, payload) => apiClient.post(`/api/projects/${projectId}/team`, payload);
export const removeTeamMember = memberId => apiClient.delete(`/api/projects/team/${memberId}`);
export const listTasks = async projectId => (await apiClient.get(`/api/projects/${projectId}/tasks`)).map(taskToUi);
export const createTask = async (projectId, payload) => taskToUi(await apiClient.post(`/api/projects/${projectId}/tasks`, taskToApi(payload)));
export const updateTask = async (taskId, payload) => taskToUi(await apiClient.put(`/api/projects/tasks/${taskId}`, taskToApi(payload)));
export const deleteTask = taskId => apiClient.delete(`/api/projects/tasks/${taskId}`);
export const listMilestones = async projectId => (await apiClient.get(`/api/projects/${projectId}/milestones`)).map(milestoneToUi);
export const createMilestone = async (projectId, payload) => milestoneToUi(await apiClient.post(`/api/projects/${projectId}/milestones`, payload));
export const updateMilestone = async (milestoneId, payload) => milestoneToUi(await apiClient.put(`/api/projects/milestones/${milestoneId}`, payload));
export const hydrateProject = async project => { const [milestones, tasks, teamMembers] = await Promise.all([listMilestones(project.id), listTasks(project.id), listTeamMembers(project.id)]); return { ...project, milestones, kanbanTasks: tasks, tasks, teamMembers }; };
export const listProjectsWithDetails = async () => Promise.all((await listProjects()).map(hydrateProject));
export const projectApi = { listProjects, getProject, listProjectsByUniversity, listProjectsByStatus, createProject, updateProject, deleteProject, listTeamMembers, addTeamMember, removeTeamMember, listTasks, createTask, updateTask, deleteTask, listMilestones, createMilestone, updateMilestone, hydrateProject, listProjectsWithDetails, mapTaskToUiModel, mapTaskToApiModel, mapMilestoneToUiModel };
